### ISSUE TITLE
Support for xivdb.com

### ISSUE THREAD

**Issue by Whispie** [surrealroad/wp-onebox#1]
Hello, I was wondering if you would consider supporting xivdb.com with your plugin?  The main documentation for their tooltips can be found here: http://xivdb.com/?tooltip

They also have a github area: https://github.com/viion/XIVDB-Tooltips

In case you're wondering, it's for a game called Final Fantasy XIV, and the tooltips cover various types of items found within.  Thank you very much for your consideration. All your efforts are very much appreciated. It's a great plugin you've made. :)

**Comment by surrealroad** [comment]
Sure, I'll look into it.

**Comment by surrealroad** [comment]
Feature added in plugin version 0.7.2, please update and let me know if you run into problems.

**Comment by Whispie** [comment]
Looks really good! Thanks so much!

**Comment by surrealroad** [comment]
:) let me know if you run into any issues
